version: "3.9"

services:

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  django:
    build:
      context: ./QA_Hub
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./QA_Hub:/usr/src/QA_Hub
    ports:
      - 8000:8000
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000 --insecure
      "
    depends_on:
      - postgres

volumes:
  postgres_data: